version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@1.5.0
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: lukybil/conint-frontend
      DOCKERHUB_USERNAME: lukybil
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    executor: node/default
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: npm run lint
          name: Run linter
  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          command: npm run test
          name: Run test
  deploy:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_ACCESS_TOKEN"
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: main